#!/usr/bin/env bash
# script that used to configer hosts to personal use

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1.*localhost$/127.0.0.2  localhost\n8.8.8.8  facebook/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
